tab_spaces = 4
hard_tabs = false
edition = "2021"
array_width = 60
chain_width = 60
imports_granularity = "Module"
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

unstable_features = true
condense_wildcard_suffixes = true
match_block_trailing_comma = true
comment_width = 100
brace_style = "SameLineWhere"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
normalize_doc_attributes = true
normalize_comments = true
wrap_comments = true
version = "Two"
use_small_heuristics = "Max"
